# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'js.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
from common import Ui_JsWindow

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JsWindow = QtWidgets.QMainWindow()
    ui = Ui_JsWindow()
    ui.setupUi(JsWindow)
    JsWindow.show()
    sys.exit(app.exec_())
